# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'StoreMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StoreMap

  pod 'SnapKit', '~> 5.0.0'

end
